Is cuda available? False
Number of different initial conditions:  2187
['gamma', 'delta', 'theta_pll', 'i_gd_g', 'i_gq_g', 'v_od_g', 'v_oq_g'] Variables
[[-0.15, 0.15], [-1.5708, 1.5708], [0, 6.283], [-2, 2], [-2, 2], [0.8, 1.2], [-0.2, 0.2]] Set of values for init conditions
[3, 3, 3, 3, 3, 3, 3] Iterations per value
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Users\h.liu\PycharmProjects\transfer-Code\My_code\create_dataset.py", line 32, in <module>
    main()
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\PycharmProjects\transfer-Code\My_code\create_dataset.py", line 26, in main
    modelling_full = GFL(config)
                     ^^^^^^^^^^^
  File "C:\Users\h.liu\PycharmProjects\transfer-Code\My_code\src\ode\gfl.py", line 25, in __init__
    self.define_model_params()  # define the parameters of the power system
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\PycharmProjects\transfer-Code\My_code\src\ode\gfl.py", line 39, in define_model_params
    model_params = OmegaConf.load(model_params_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\h.liu\AppData\Roaming\Python\Python311\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\h.liu\\PycharmProjects\\transfer-Code\\My_code\\src\\conf\\params\\GFL_7th_order1.yaml'
